#!/bin/bash

Syntax() {
	echo " "
	echo "  Command Syntax: check_solaris_swap [-H host] [-c val] [-w val]"
	echo " "
	exit 3
}

if [[ $# -ne 6 ]]; then
	Syntax
fi

while
	[[ $# > 0 ]]
do
	par=$1
	case $par in
	-c)
		shift
		valc=$1
		;;
	-w)
		shift
		valw=$1
		;;
	-H)
		shift
		host=$1
		;;
	-h)
		shift
		Syntax
		exit
		;;
	*) shift ;;
	esac
done

valc=$(echo "$valc*1.0" | bc)
valw=$(echo "$valw*1.0" | bc)

response=$(ssh nagios@$host "/usr/sbin/swap -s")
if [[ -z $response ]]; then
	echo "SSH Error"
	exit 3
fi

used=$(echo "$response" | awk '{print $9}')
used=${used::${#used}-1}

available=$(echo "$response" | awk '{print $11}')
available=${available::${#available}-1}

percentageUsed=$(echo "scale=2;($used / ($used + $available)) * 100" | bc -l)

exitCode=0
status="OK"

if (($(echo "$percentageUsed > $valw" | bc -l))); then
	exitCode=1
	status="WARNING"
fi

if (($(echo "$percentageUsed > $valc" | bc -l))); then
	exitCode=2
	status="CRITICAL"
fi

echo "SWAP $status :: SwapUsed = $percentageUsed% | SwapUsed=$percentageUsed%;$valw;$valc"
exit $exitCode
