#!/bin/bash

if [[ -z $1 ]]
then
	echo "Host argument missing"
	exit 3
fi

rawOutput=$(ssh nagios@$1 "cat /proc/cpuinfo")
if [[ -z $rawOutput ]]
then
	echo "SSH Error"
	exit 3
fi

sockets=$(echo "{$rawOutput}" | grep "physical id" | sort -u | wc -l)
coresPerSocket=$(echo "{$rawOutput}" | grep "cpu cores" | sort -u | cut -d':' -f 2)
totalCores=$(echo "$(($sockets * $coresPerSocket))")

echo "Total Cores: $totalCores // Sockets: $sockets // Cores per socket: $coresPerSocket"
