#!/bin/bash

if [[ -z $1 ]]
then
	echo "Host argument missing"
	exit 3
fi

rawOutput=$(ssh nagios@$1 "cat /proc/cpuinfo")
if [[ -z $rawOutput ]]
then
	echo "SSH Error"
	exit 3
fi

sockets=$(echo "{$rawOutput}" | grep "physical id" | sort -u | wc -l)
if [[ $sockets -eq "0" ]]
then
	sockets=1
fi

coresPerSocket=$(echo "{$rawOutput}" | grep "cpu cores" | sort -u | cut -d':' -f 2)
if [[ $coresPerSocket -eq "0" ]]
then
	coresPerSocket=1
fi

totalCores=$(echo "$(($sockets * $coresPerSocket))")

cpuName=$(echo "{$rawOutput}" | grep -m 1 "model name" | cut -d':' -f 2)

echo "$cpuName // Total Cores: $totalCores // Sockets: $sockets // Cores per socket: $coresPerSocket"
