#!/bin/bash

Syntaxe()
{
   echo " "
   echo "  Command Syntaxe: check_solaris_cpu [-H host] [-c val] [-w val] "
   echo " "
   exit 3;
}

if [[ $# -ne 6 ]]
then
  Syntaxe
fi

valw=0
valc=0
host=""

while [[ $# > 0 ]]
do
   par=$1
   case $par in
     -c) shift
         valc=$1;;
     -w) shift
         valw=$1;;
     -H) shift
         host=$1;;
     -h) shift
         Syntaxe
         exit;;
      *) shift;;
   esac
done


if [[ $valc -lt $valw ]]
then
        echo "Warning value must be less than the critical value"
        exit 3
fi

output=$(ssh nagios@$host "/usr/bin/vmstat 1 3 | /bin/egrep -v 'Time|kthr' | /bin/awk '{print \$22}'|/usr/bin/tail -1")
output=$((100-output))

if (( $output >= $valc )) 
then
        echo "CPU CRITICAL: Total $output% | total=$output%"
        exit 2

elif (( $output >= $valw )) 
then
        echo "CPU WARNING: Total $output% | total=$output%"
        exit 1

elif (( $output < $valw ))
then
        echo "CPU OK: Total $output% | total=$output%"
        exit 0
else
        echo "CPU UNKNOWN"
        exit 3 
fi
